// Code generated by "stringer -type=EncodingEnum"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNICODE-0]
	_ = x[ANSI-1]
}

const _EncodingEnum_name = "UNICODEANSI"

var _EncodingEnum_index = [...]uint8{0, 7, 11}

func (i EncodingEnum) String() string {
	if i < 0 || i >= EncodingEnum(len(_EncodingEnum_index)-1) {
		return "EncodingEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EncodingEnum_name[_EncodingEnum_index[i]:_EncodingEnum_index[i+1]]
}
