// Code generated by "stringer -type=SupportedFileFormatEnum"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXCEL-0]
	_ = x[WORD-1]
	_ = x[TXT-2]
}

const _SupportedFileFormatEnum_name = "EXCELWORDTXT"

var _SupportedFileFormatEnum_index = [...]uint8{0, 5, 9, 12}

func (i SupportedFileFormatEnum) String() string {
	if i < 0 || i >= SupportedFileFormatEnum(len(_SupportedFileFormatEnum_index)-1) {
		return "SupportedFileFormatEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SupportedFileFormatEnum_name[_SupportedFileFormatEnum_index[i]:_SupportedFileFormatEnum_index[i+1]]
}
